# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  projectDirectory: 'kronic_desktop_tool'

trigger:
- master

jobs:
  - job: WindowsBuild
    pool:
      vmImage: 'windows-2022'
    steps:
    - task: FlutterInstall@0
      inputs:
        mode: 'auto'
        channel: 'stable'
        version: 'latest'

    - task: FlutterCommand@0
      inputs:
          projectDirectory: '.'
          arguments: 'config --enable-windows-desktop'
    - task: FlutterBuild@0
      inputs:
        target: 'windows'
        projectDirectory: '.'
    